name: Workflow for incoming changes
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "check"
            python: "3.9"
            toxpython: "python3.9"
            tox_env: "check"
            os: "ubuntu-latest"
          - name: "py38 (ubuntu)"
            python: "3.8"
            toxpython: "python3.8"
            python_arch: "x64"
            tox_env: "py38"
            os: "ubuntu-latest"
          - name: "py38 (windows)"
            python: "3.8"
            toxpython: "python3.8"
            python_arch: "x64"
            tox_env: "py38"
            os: "windows-latest"
          - name: "py38 (macos)"
            python: "3.8"
            toxpython: "python3.8"
            python_arch: "x64"
            tox_env: "py38"
            os: "macos-latest"
          - name: "py39 (ubuntu)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39"
            os: "ubuntu-latest"
          - name: "py39 (windows)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39"
            os: "windows-latest"
          - name: "py39 (macos)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39"
            os: "macos-latest"
          - name: "py310 (ubuntu)"
            python: "3.10"
            toxpython: "python3.10"
            python_arch: "x64"
            tox_env: "py310"
            os: "ubuntu-latest"
          - name: "py310 (windows)"
            python: "3.10"
            toxpython: "python3.10"
            python_arch: "x64"
            tox_env: "py310"
            os: "windows-latest"
          - name: "py310 (macos)"
            python: "3.10"
            toxpython: "python3.10"
            python_arch: "x64"
            tox_env: "py310"
            os: "macos-latest"
          - name: "pypy38 (ubuntu)"
            python: "pypy-3.8"
            toxpython: "pypy3.8"
            python_arch: "x64"
            tox_env: "pypy38"
            os: "ubuntu-latest"
          - name: "pypy38 (windows)"
            python: "pypy-3.8"
            toxpython: "pypy3.8"
            python_arch: "x64"
            tox_env: "pypy38"
            os: "windows-latest"
          - name: "pypy38 (macos)"
            python: "pypy-3.8"
            toxpython: "pypy3.8"
            python_arch: "x64"
            tox_env: "pypy38"
            os: "macos-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.python_arch }}
      - name: install dependencies
        run: |
          python -mpip install --progress-bar=off -r ci/requirements.txt
          virtualenv --version
          pip --version
          tox --version
          pip list --format=freeze
      - name: "Run tox targets for ${{ matrix.python }}"
        env:
          TOXPYTHON: "${{ matrix.toxpython }}"
        run: python -m tox -e ${{ matrix.tox_env }}
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
