name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    env:
      USING_COVERAGE: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -mpip install --progress-bar=off -r ci/requirements.txt
          virtualenv --version
          pip --version
          tox --version
          pip list --format=freeze
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox
      - name: Upload coverage reports to Codecov
        if: contains(env.USING_COVERAGE, matrix.python-version) && (matrix.os == "ubuntu-latest")
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
