name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    env:
      USING_COVERAGE: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -mpip install --progress-bar=off -r ci/requirements.txt
          virtualenv --version
          pip --version
          tox --version
          pip list --format=freeze
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
